### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by chrzyki**

### CODE REVIEW

**Review by FredericBlum — COMMENTED** [review]
The citation in the metadata is given as 2018, but in all other places it is 2019. Could you check which one is correct?

**Comment by chrzyki** [comment]
The segmented data on Zenodo is dated to 2018 (in accordance with the deposit on Zenodo):

```bib
@book{walworth_mary_2018_1689909,
  author       = {Walworth, Mary},
  title        = {Polynesian segmented data},
  year = {2018},
  doi          = {10.5281/zenodo.1689909},
  url          = {https://doi.org/10.5281/zenodo.1689909},
  address = {Genève},
  publisher = {Zenodo}
}
```

**Comment by FredericBlum** [comment]
Should we then adapt the whole repo to 2018?

**Comment by chrzyki** [comment]
Changed to 2018.

**Pull request merged**
